2017-07-10 23:11:21,382 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x034067F0>, 'Connection to 111.243.96.109 timed out. (connect timeout=20)'))
2017-07-10 23:13:06,928 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x035167F0>, 'Connection to 111.243.96.109 timed out. (connect timeout=20)'))
