2017-07-02 17:58:05,669 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03A1E230>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 17:58:25,698 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x039DCEB0>, 'Connection to 59.66.135.35 timed out. (connect timeout=20)'))
2017-07-02 18:43:40,919 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E130B0>, 'Connection to 118.117.138.80 timed out. (connect timeout=20)'))
2017-07-02 18:44:00,923 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13530>, 'Connection to 117.90.137.3 timed out. (connect timeout=20)'))
2017-07-02 18:44:02,077 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E139B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:44:22,081 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13E30>, 'Connection to 182.42.39.111 timed out. (connect timeout=20)'))
2017-07-02 18:44:42,086 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042882D0>, 'Connection to 123.247.142.100 timed out. (connect timeout=20)'))
2017-07-02 18:44:43,390 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13ED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:44:44,433 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13870>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:45:04,436 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E134F0>, 'Connection to 182.129.240.160 timed out. (connect timeout=20)'))
2017-07-02 18:45:24,445 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2650>, 'Connection to 60.214.154.2 timed out. (connect timeout=20)'))
2017-07-02 18:45:44,451 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288050>, 'Connection to 117.90.3.125 timed out. (connect timeout=20)'))
2017-07-02 18:45:50,565 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288A90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:45:50,773 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 18:46:10,782 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288F90>, 'Connection to 118.117.138.232 timed out. (connect timeout=20)'))
2017-07-02 18:46:11,956 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042886F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:46:31,961 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288250>, 'Connection to 117.90.0.178 timed out. (connect timeout=20)'))
2017-07-02 18:46:32,981 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:46:52,986 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13A90>, 'Connection to 117.64.235.202 timed out. (connect timeout=20)'))
2017-07-02 18:47:12,991 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13C70>, 'Connection to 115.226.133.152 timed out. (connect timeout=20)'))
2017-07-02 18:47:32,999 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E138D0>, 'Connection to 163.125.223.124 timed out. (connect timeout=20)'))
2017-07-02 18:47:53,003 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13DF0>, 'Connection to 121.31.103.170 timed out. (connect timeout=20)'))
2017-07-02 18:47:54,060 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03E13210>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:47:55,137 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042883F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:48:15,143 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042886D0>, 'Connection to 183.154.213.90 timed out. (connect timeout=20)'))
2017-07-02 18:48:16,380 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:48:36,384 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299030>, 'Connection to 114.97.245.55 timed out. (connect timeout=20)'))
2017-07-02 18:48:56,391 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288D90>, 'Connection to 117.90.6.73 timed out. (connect timeout=20)'))
2017-07-02 18:48:56,470 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 18:49:16,474 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288850>, 'Connection to 103.235.242.70 timed out. (connect timeout=20)'))
2017-07-02 18:49:17,511 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:49:23,935 utilFunction.py[line:25] INFO 111.12.96.188:80 is ok!
2017-07-02 18:49:43,944 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288530>, 'Connection to 171.80.160.145 timed out. (connect timeout=20)'))
2017-07-02 18:49:45,020 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042996D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:50:05,024 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2F50>, 'Connection to 121.232.148.146 timed out. (connect timeout=20)'))
2017-07-02 18:50:25,032 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288050>, 'Connection to 117.90.2.221 timed out. (connect timeout=20)'))
2017-07-02 18:50:45,038 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288090>, 'Connection to 121.232.146.102 timed out. (connect timeout=20)'))
2017-07-02 18:51:05,042 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042886B0>, 'Connection to 114.99.10.94 timed out. (connect timeout=20)'))
2017-07-02 18:51:06,186 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:51:26,190 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299950>, 'Connection to 171.39.29.210 timed out. (connect timeout=20)'))
2017-07-02 18:51:46,195 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299730>, 'Connection to 163.125.249.254 timed out. (connect timeout=20)'))
2017-07-02 18:52:06,201 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288BF0>, 'Connection to 39.67.117.12 timed out. (connect timeout=20)'))
2017-07-02 18:52:26,207 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288F90>, 'Connection to 163.125.249.112 timed out. (connect timeout=20)'))
2017-07-02 18:52:46,214 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288130>, 'Connection to 103.235.242.70 timed out. (connect timeout=20)'))
2017-07-02 18:52:47,328 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF2A70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:53:07,332 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299B90>, 'Connection to 121.232.146.188 timed out. (connect timeout=20)'))
2017-07-02 18:53:27,337 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299590>, 'Connection to 121.232.147.175 timed out. (connect timeout=20)'))
2017-07-02 18:53:30,880 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:53:50,884 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03DF27B0>, 'Connection to 121.232.145.161 timed out. (connect timeout=20)'))
2017-07-02 18:54:10,888 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288C30>, 'Connection to 60.178.174.156 timed out. (connect timeout=20)'))
2017-07-02 18:54:11,961 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288F30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:54:29,825 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-02 18:54:49,829 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042886F0>, 'Connection to 60.178.11.74 timed out. (connect timeout=20)'))
2017-07-02 18:55:09,834 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299710>, 'Connection to 111.202.121.133 timed out. (connect timeout=20)'))
2017-07-02 18:55:10,003 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-02 18:55:11,046 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042999B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:55:31,053 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299C30>, 'Connection to 117.90.2.86 timed out. (connect timeout=20)'))
2017-07-02 18:55:51,059 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042885F0>, 'Connection to 117.90.0.168 timed out. (connect timeout=20)'))
2017-07-02 18:56:11,062 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04288850>, 'Connection to 117.90.0.24 timed out. (connect timeout=20)'))
2017-07-02 18:56:31,067 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x042888F0>, 'Connection to 117.90.1.116 timed out. (connect timeout=20)'))
2017-07-02 18:56:32,107 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03B252F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:56:52,111 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299250>, 'Connection to 117.90.0.153 timed out. (connect timeout=20)'))
2017-07-02 18:57:12,116 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04299070>, 'Connection to 163.125.251.21 timed out. (connect timeout=20)'))
2017-07-02 18:58:55,517 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C47D90>, 'Connection to 182.129.241.107 timed out. (connect timeout=20)'))
2017-07-02 18:59:15,522 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04785230>, 'Connection to 118.117.138.80 timed out. (connect timeout=20)'))
2017-07-02 18:59:15,562 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-02 18:59:22,245 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C35C10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 18:59:49,238 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-02 19:00:09,175 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FB1AD0>, 'Connection to 182.129.241.107 timed out. (connect timeout=20)'))
2017-07-02 19:00:09,183 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FBFA30>, 'Connection to 118.117.138.80 timed out. (connect timeout=20)'))
2017-07-02 19:00:09,186 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FBFC90>, 'Connection to 117.90.7.22 timed out. (connect timeout=20)'))
2017-07-02 19:00:09,186 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC9130>, 'Connection to 182.42.39.111 timed out. (connect timeout=20)'))
2017-07-02 19:00:09,243 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FBF2D0>, 'Connection to 123.247.142.100 timed out. (connect timeout=20)'))
2017-07-02 19:00:10,221 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC95D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:10,236 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC9930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:10,311 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 19:00:20,064 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC92B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:29,195 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x050FB1B0>, 'Connection to 182.129.240.160 timed out. (connect timeout=20)'))
2017-07-02 19:00:29,195 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FB1890>, 'Connection to 60.214.154.2 timed out. (connect timeout=20)'))
2017-07-02 19:00:29,247 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x050FB5F0>, 'Connection to 117.90.3.125 timed out. (connect timeout=20)'))
2017-07-02 19:00:30,243 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FB1A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:30,296 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x050FB7D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:30,317 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FBF270>, 'Connection to 118.117.138.232 timed out. (connect timeout=20)'))
2017-07-02 19:00:40,085 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-02 19:00:45,888 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC9290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:00:46,056 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 19:00:49,201 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FB1D50>, 'Connection to 123.247.142.100 timed out. (connect timeout=20)'))
2017-07-02 19:00:50,247 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x050FBA10>, 'Connection to 182.129.240.160 timed out. (connect timeout=20)'))
2017-07-02 19:00:50,323 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03FC9490>, 'Connection to 117.90.3.125 timed out. (connect timeout=20)'))
2017-07-02 19:00:53,329 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-02 19:00:59,430 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-02 19:01:06,060 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x050FB7B0>, 'Connection to 118.117.138.232 timed out. (connect timeout=20)'))
2017-07-02 19:02:28,801 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C340F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:02:47,778 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C23B70>, 'Connection to 117.90.0.178 timed out. (connect timeout=20)'))
2017-07-02 19:02:47,786 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34F10>, 'Connection to 117.64.235.202 timed out. (connect timeout=20)'))
2017-07-02 19:02:47,787 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34CD0>, 'Connection to 163.125.223.124 timed out. (connect timeout=20)'))
2017-07-02 19:02:47,788 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34A50>, 'Connection to 115.226.133.152 timed out. (connect timeout=20)'))
2017-07-02 19:02:48,805 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C3E3F0>, 'Connection to 121.31.103.170 timed out. (connect timeout=20)'))
2017-07-02 19:02:48,867 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C3ED70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:02:49,911 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C3E210>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:02:49,992 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 19:03:07,787 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C3E450>, 'Connection to 117.90.0.173 timed out. (connect timeout=20)'))
2017-07-02 19:03:07,802 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C30030>, 'Connection to 183.154.213.90 timed out. (connect timeout=20)'))
2017-07-02 19:03:07,805 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C30230>, 'Connection to 117.90.2.125 timed out. (connect timeout=20)'))
2017-07-02 19:03:08,809 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C306D0>, 'Connection to 114.97.245.55 timed out. (connect timeout=20)'))
2017-07-02 19:03:08,834 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34C10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:03:09,893 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C30670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:03:09,997 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34C90>, 'Connection to 103.235.242.70 timed out. (connect timeout=20)'))
2017-07-02 19:03:27,810 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C23D70>, 'Connection to 171.80.160.145 timed out. (connect timeout=20)'))
2017-07-02 19:03:28,427 utilFunction.py[line:25] INFO 111.12.96.188:80 is ok!
2017-07-02 19:03:28,841 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C30B50>, 'Connection to 121.232.148.146 timed out. (connect timeout=20)'))
2017-07-02 19:03:29,572 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C348D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:03:29,896 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C23830>, 'Connection to 117.90.2.221 timed out. (connect timeout=20)'))
2017-07-02 19:03:30,003 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34AF0>, 'Connection to 121.232.146.102 timed out. (connect timeout=20)'))
2017-07-02 19:03:47,815 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C30890>, 'Connection to 114.99.10.94 timed out. (connect timeout=20)'))
2017-07-02 19:03:48,846 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34530>, 'Connection to 171.39.29.210 timed out. (connect timeout=20)'))
2017-07-02 19:03:49,576 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F1370>, 'Connection to 163.125.249.254 timed out. (connect timeout=20)'))
2017-07-02 19:03:49,902 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F17F0>, 'Connection to 39.67.117.12 timed out. (connect timeout=20)'))
2017-07-02 19:03:49,987 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F1D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:03:50,007 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C305F0>, 'Connection to 163.125.249.112 timed out. (connect timeout=20)'))
2017-07-02 19:03:56,954 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error',)))
2017-07-02 19:03:58,176 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
2017-07-02 19:04:01,745 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:04:07,819 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F1890>, 'Connection to 103.235.242.70 timed out. (connect timeout=20)'))
2017-07-02 19:04:09,906 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041690>, 'Connection to 121.232.147.175 timed out. (connect timeout=20)'))
2017-07-02 19:04:10,011 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041B70>, 'Connection to 121.232.145.161 timed out. (connect timeout=20)'))
2017-07-02 19:04:10,207 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-02 19:04:11,251 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:04:16,959 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041910>, 'Connection to 60.178.174.156 timed out. (connect timeout=20)'))
2017-07-02 19:04:21,778 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-02 19:04:27,823 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050370>, 'Connection to 60.178.11.74 timed out. (connect timeout=20)'))
2017-07-02 19:04:29,912 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050810>, 'Connection to 111.202.121.133 timed out. (connect timeout=20)'))
2017-07-02 19:04:31,256 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C34950>, 'Connection to 117.90.2.86 timed out. (connect timeout=20)'))
2017-07-02 19:04:36,964 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F18D0>, 'Connection to 117.90.0.168 timed out. (connect timeout=20)'))
2017-07-02 19:04:41,783 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041DB0>, 'Connection to 117.90.0.24 timed out. (connect timeout=20)'))
2017-07-02 19:04:47,826 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050A10>, 'Connection to 117.90.1.116 timed out. (connect timeout=20)'))
2017-07-02 19:04:48,865 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:04:49,916 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050FF0>, 'Connection to 117.90.2.151 timed out. (connect timeout=20)'))
2017-07-02 19:04:51,261 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E490>, 'Connection to 117.90.0.153 timed out. (connect timeout=20)'))
2017-07-02 19:04:56,967 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E910>, 'Connection to 163.125.251.21 timed out. (connect timeout=20)'))
2017-07-02 19:05:01,787 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03C23070>, 'Connection to 121.232.145.181 timed out. (connect timeout=20)'))
2017-07-02 19:05:02,190 utilFunction.py[line:25] INFO 120.77.206.98:8118 is ok!
2017-07-02 19:05:08,869 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041B10>, 'Connection to 117.90.6.31 timed out. (connect timeout=20)'))
2017-07-02 19:05:09,919 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405EE70>, 'Connection to 163.125.250.61 timed out. (connect timeout=20)'))
2017-07-02 19:05:11,264 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406B310>, 'Connection to 121.40.40.182 timed out. (connect timeout=20)'))
2017-07-02 19:05:12,312 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406BF70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:05:15,305 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405EC50>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)))
2017-07-02 19:05:15,402 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))
2017-07-02 19:05:16,973 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041070>, 'Connection to 117.90.1.76 timed out. (connect timeout=20)'))
2017-07-02 19:05:28,873 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406B870>, 'Connection to 120.9.12.183 timed out. (connect timeout=20)'))
2017-07-02 19:05:28,980 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-02 19:05:29,924 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406BAD0>, 'Connection to 182.129.241.185 timed out. (connect timeout=20)'))
2017-07-02 19:05:32,316 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B430>, 'Connection to 117.90.2.235 timed out. (connect timeout=20)'))
2017-07-02 19:05:33,428 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:05:35,405 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04041D90>, 'Connection to 114.230.41.195 timed out. (connect timeout=20)'))
2017-07-02 19:05:36,977 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x051F1B50>, 'Connection to 115.202.188.50 timed out. (connect timeout=20)'))
2017-07-02 19:05:48,984 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B6F0>, 'Connection to 114.99.13.49 timed out. (connect timeout=20)'))
2017-07-02 19:05:49,927 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407BC10>, 'Connection to 125.67.74.219 timed out. (connect timeout=20)'))
2017-07-02 19:05:52,971 utilFunction.py[line:31] ERROR ('Connection aborted.', BadStatusLine('<html>\r\n',))
2017-07-02 19:05:53,434 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A570>, 'Connection to 116.204.64.97 timed out. (connect timeout=20)'))
2017-07-02 19:05:54,530 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:05:55,410 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B0D0>, 'Connection to 117.90.1.129 timed out. (connect timeout=20)'))
2017-07-02 19:05:56,986 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A0D0>, 'Connection to 110.73.29.108 timed out. (connect timeout=20)'))
2017-07-02 19:05:58,125 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:06:08,988 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0AAB0>, 'Connection to 27.46.55.1 timed out. (connect timeout=20)'))
2017-07-02 19:06:12,975 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406BD30>, 'Connection to 117.90.4.108 timed out. (connect timeout=20)'))
2017-07-02 19:06:14,536 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19210>, 'Connection to 163.125.221.73 timed out. (connect timeout=20)'))
2017-07-02 19:06:15,414 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19B30>, 'Connection to 110.73.156.65 timed out. (connect timeout=20)'))
2017-07-02 19:06:15,589 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28DD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:06:18,130 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28470>, 'Connection to 116.90.84.250 timed out. (connect timeout=20)'))
2017-07-02 19:06:28,992 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B288D0>, 'Connection to 219.228.126.86 timed out. (connect timeout=20)'))
2017-07-02 19:06:32,980 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19B70>, 'Connection to 117.90.1.29 timed out. (connect timeout=20)'))
2017-07-02 19:06:34,017 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28BD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:06:35,419 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B286B0>, 'Connection to 60.179.124.203 timed out. (connect timeout=20)'))
2017-07-02 19:06:35,594 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B334D0>, 'Connection to 59.78.44.244 timed out. (connect timeout=20)'))
2017-07-02 19:06:38,134 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33950>, 'Connection to 121.31.151.132 timed out. (connect timeout=20)'))
2017-07-02 19:06:48,995 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33DF0>, 'Connection to 163.125.221.201 timed out. (connect timeout=20)'))
2017-07-02 19:06:50,040 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B54130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:06:54,021 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19DF0>, 'Connection to 117.90.1.142 timed out. (connect timeout=20)'))
2017-07-02 19:06:55,423 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B47330>, 'Connection to 171.215.226.223 timed out. (connect timeout=20)'))
2017-07-02 19:06:55,599 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B477D0>, 'Connection to 163.125.221.113 timed out. (connect timeout=20)'))
2017-07-02 19:06:58,140 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B47C70>, 'Connection to 182.32.238.224 timed out. (connect timeout=20)'))
2017-07-02 19:07:10,045 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B47D90>, 'Connection to 117.90.3.242 timed out. (connect timeout=20)'))
2017-07-02 19:07:14,026 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33C70>, 'Connection to 163.125.221.233 timed out. (connect timeout=20)'))
2017-07-02 19:07:15,427 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33310>, 'Connection to 121.232.145.33 timed out. (connect timeout=20)'))
2017-07-02 19:07:15,604 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B288F0>, 'Connection to 117.28.61.154 timed out. (connect timeout=20)'))
2017-07-02 19:07:18,145 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28810>, 'Connection to 121.232.144.200 timed out. (connect timeout=20)'))
2017-07-02 19:07:30,049 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28030>, 'Connection to 210.45.121.106 timed out. (connect timeout=20)'))
2017-07-02 19:07:34,029 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19A50>, 'Connection to 121.232.148.146 timed out. (connect timeout=20)'))
2017-07-02 19:07:35,433 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33950>, 'Connection to 180.118.241.218 timed out. (connect timeout=20)'))
2017-07-02 19:07:35,609 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B471F0>, 'Connection to 117.90.4.75 timed out. (connect timeout=20)'))
2017-07-02 19:07:38,150 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B47090>, 'Connection to 112.66.61.103 timed out. (connect timeout=20)'))
2017-07-02 19:07:39,276 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B28EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:40,407 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:41,558 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B337F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:42,604 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:42,632 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 19:07:43,759 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:43,849 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-02 19:07:43,870 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))
2017-07-02 19:07:45,015 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:46,064 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407BA10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:47,205 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:48,265 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:49,405 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A2B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:50,053 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19750>, 'Connection to 115.210.28.65 timed out. (connect timeout=20)'))
2017-07-02 19:07:50,478 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:51,202 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B47FF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:52,256 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407BD10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:54,032 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B192F0>, 'Connection to 117.90.3.4 timed out. (connect timeout=20)'))
2017-07-02 19:07:55,180 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A3D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:07:55,436 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0AC90>, 'Connection to 59.66.135.35 timed out. (connect timeout=20)'))
2017-07-02 19:07:55,613 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0AED0>, 'Connection to 117.90.1.93 timed out. (connect timeout=20)'))
2017-07-02 19:08:10,482 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407BD50>, 'Connection to 117.90.7.231 timed out. (connect timeout=20)'))
2017-07-02 19:08:10,573 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-02 19:08:12,260 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B288D0>, 'Connection to 117.90.1.211 timed out. (connect timeout=20)'))
2017-07-02 19:08:15,184 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19F90>, 'Connection to 121.232.146.234 timed out. (connect timeout=20)'))
2017-07-02 19:08:15,442 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33E10>, 'Connection to 1.83.107.30 timed out. (connect timeout=20)'))
2017-07-02 19:08:15,617 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B3F0>, 'Connection to 117.90.137.3 timed out. (connect timeout=20)'))
2017-07-02 19:08:17,305 utilFunction.py[line:25] INFO 124.72.216.247:808 is ok!
2017-07-02 19:08:18,444 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A270>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:18,750 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A930>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:19,378 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B288B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:19,764 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406BCB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:30,576 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407BF90>, 'Connection to 182.129.241.7 timed out. (connect timeout=20)'))
2017-07-02 19:08:32,263 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B050>, 'Connection to 117.90.5.157 timed out. (connect timeout=20)'))
2017-07-02 19:08:38,756 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406BE30>, 'Connection to 114.99.5.75 timed out. (connect timeout=20)'))
2017-07-02 19:08:39,383 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0406B690>, 'Connection to 182.129.241.107 timed out. (connect timeout=20)'))
2017-07-02 19:08:39,770 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E9B0>, 'Connection to 118.117.138.80 timed out. (connect timeout=20)'))
2017-07-02 19:08:40,954 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405ECD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:41,993 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E450>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:08:50,582 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0407B910>, 'Connection to 117.90.137.3 timed out. (connect timeout=20)'))
2017-07-02 19:08:52,266 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B33370>, 'Connection to 117.90.7.22 timed out. (connect timeout=20)'))
2017-07-02 19:08:58,763 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B0A7B0>, 'Connection to 182.42.39.111 timed out. (connect timeout=20)'))
2017-07-02 19:08:59,386 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00B19250>, 'Connection to 123.247.142.100 timed out. (connect timeout=20)'))
2017-07-02 19:08:59,459 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-02 19:09:01,997 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E330>, 'Connection to 182.129.240.160 timed out. (connect timeout=20)'))
2017-07-02 19:09:02,033 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-02 19:09:06,466 utilFunction.py[line:25] INFO 60.214.154.2:53281 is ok!
2017-07-02 19:09:06,940 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050A50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-02 19:09:12,272 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0405E1D0>, 'Connection to 117.90.3.125 timed out. (connect timeout=20)'))
2017-07-02 19:09:19,465 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x04050E30>, 'Connection to 118.117.138.232 timed out. (connect timeout=20)'))
2017-07-03 00:15:13,609 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x038EF210>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 00:15:13,751 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 00:15:13,877 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))
2017-07-03 00:15:31,927 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-03 15:42:45,605 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-03 15:42:46,592 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D71DF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:05,489 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D64C90>, 'Connection to 114.99.10.94 timed out. (connect timeout=20)'))
2017-07-03 15:43:05,490 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D30790>, 'Connection to 39.67.117.12 timed out. (connect timeout=20)'))
2017-07-03 15:43:05,494 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D070>, 'Connection to 171.39.29.210 timed out. (connect timeout=20)'))
2017-07-03 15:43:05,661 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D64E50>, 'Connection to 163.125.249.112 timed out. (connect timeout=20)'))
2017-07-03 15:43:06,532 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7DEB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:06,603 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D530>, 'Connection to 103.235.242.70 timed out. (connect timeout=20)'))
2017-07-03 15:43:06,608 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D710>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:07,595 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x053108B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:12,822 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-03 15:43:13,089 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error',)))
2017-07-03 15:43:16,641 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-03 15:43:25,498 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D930>, 'Connection to 121.232.146.188 timed out. (connect timeout=20)'))
2017-07-03 15:43:26,600 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D64F90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:26,612 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7DBF0>, 'Connection to 60.178.174.156 timed out. (connect timeout=20)'))
2017-07-03 15:43:26,616 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D170>, 'Connection to 117.90.5.138 timed out. (connect timeout=20)'))
2017-07-03 15:43:33,091 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D71370>, 'Connection to 60.178.11.74 timed out. (connect timeout=20)'))
2017-07-03 15:43:36,644 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D71E90>, 'Connection to 111.202.121.133 timed out. (connect timeout=20)'))
2017-07-03 15:43:46,613 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D64830>, 'Connection to 121.232.144.81 timed out. (connect timeout=20)'))
2017-07-03 15:43:46,620 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05310070>, 'Connection to 117.90.2.86 timed out. (connect timeout=20)'))
2017-07-03 15:43:46,623 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05310C90>, 'Connection to 117.90.0.168 timed out. (connect timeout=20)'))
2017-07-03 15:43:46,664 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-03 15:43:53,095 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D711D0>, 'Connection to 117.90.0.24 timed out. (connect timeout=20)'))
2017-07-03 15:43:56,648 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D910>, 'Connection to 117.90.1.116 timed out. (connect timeout=20)'))
2017-07-03 15:43:57,693 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D14F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:43:58,807 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D71430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:05,144 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D750>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)))
2017-07-03 15:44:06,636 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05310FB0>, 'Connection to 163.125.251.21 timed out. (connect timeout=20)'))
2017-07-03 15:44:06,671 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7D2B0>, 'Connection to 121.232.145.181 timed out. (connect timeout=20)'))
2017-07-03 15:44:06,714 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:44:07,758 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D712B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:13,104 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05321490>, 'Connection to 121.232.144.226 timed out. (connect timeout=20)'))
2017-07-03 15:44:14,151 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D7DA10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:18,812 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05321990>, 'Connection to 121.40.40.182 timed out. (connect timeout=20)'))
2017-07-03 15:44:18,888 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request',)))
2017-07-03 15:44:19,926 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532CA10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:25,246 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05321E10>, 'Connection to 117.90.1.76 timed out. (connect timeout=20)'))
2017-07-03 15:44:25,343 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-03 15:44:26,718 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C250>, 'Connection to 120.9.12.183 timed out. (connect timeout=20)'))
2017-07-03 15:44:27,764 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C990>, 'Connection to 182.129.241.185 timed out. (connect timeout=20)'))
2017-07-03 15:44:34,154 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x053216D0>, 'Connection to 117.90.2.235 timed out. (connect timeout=20)'))
2017-07-03 15:44:39,932 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532CF50>, 'Connection to 115.202.188.50 timed out. (connect timeout=20)'))
2017-07-03 15:44:40,970 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533CBD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:45,347 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x05321B70>, 'Connection to 114.99.13.49 timed out. (connect timeout=20)'))
2017-07-03 15:44:46,721 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C670>, 'Connection to 125.67.74.219 timed out. (connect timeout=20)'))
2017-07-03 15:44:47,770 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D713F0>, 'Connection to 163.125.221.142 timed out. (connect timeout=20)'))
2017-07-03 15:44:54,157 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C730>, 'Connection to 116.204.64.97 timed out. (connect timeout=20)'))
2017-07-03 15:44:55,221 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:44:56,344 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:00,974 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C090>, 'Connection to 110.73.29.108 timed out. (connect timeout=20)'))
2017-07-03 15:45:02,121 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:05,352 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C530>, 'Connection to 27.46.55.1 timed out. (connect timeout=20)'))
2017-07-03 15:45:06,724 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533CBD0>, 'Connection to 60.211.60.249 timed out. (connect timeout=20)'))
2017-07-03 15:45:07,775 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CA30>, 'Connection to 117.90.4.108 timed out. (connect timeout=20)'))
2017-07-03 15:45:08,819 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:10,266 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:12,534 utilFunction.py[line:25] INFO 59.78.44.244:8123 is ok!
2017-07-03 15:45:16,347 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C695B0>, 'Connection to 110.73.156.65 timed out. (connect timeout=20)'))
2017-07-03 15:45:22,124 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CF10>, 'Connection to 116.90.84.250 timed out. (connect timeout=20)'))
2017-07-03 15:45:23,220 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:24,350 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78CB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:45:25,356 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CB30>, 'Connection to 219.228.126.86 timed out. (connect timeout=20)'))
2017-07-03 15:45:28,824 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78470>, 'Connection to 60.179.124.203 timed out. (connect timeout=20)'))
2017-07-03 15:45:32,539 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69910>, 'Connection to 121.31.151.132 timed out. (connect timeout=20)'))
2017-07-03 15:45:36,350 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C6F0>, 'Connection to 163.125.221.201 timed out. (connect timeout=20)'))
2017-07-03 15:45:44,353 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0146C150>, 'Connection to 171.215.226.223 timed out. (connect timeout=20)'))
2017-07-03 15:45:45,359 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0146C5D0>, 'Connection to 163.125.221.113 timed out. (connect timeout=20)'))
2017-07-03 15:45:48,830 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C784F0>, 'Connection to 182.32.238.224 timed out. (connect timeout=20)'))
2017-07-03 15:45:52,544 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C310>, 'Connection to 117.90.4.194 timed out. (connect timeout=20)'))
2017-07-03 15:45:56,353 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0146CB30>, 'Connection to 117.90.3.242 timed out. (connect timeout=20)'))
2017-07-03 15:45:57,401 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78A50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:04,356 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0146CFD0>, 'Connection to 163.125.221.233 timed out. (connect timeout=20)'))
2017-07-03 15:46:05,365 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C9B0>, 'Connection to 121.232.145.33 timed out. (connect timeout=20)'))
2017-07-03 15:46:07,887 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:08,834 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147B6D0>, 'Connection to 117.28.61.154 timed out. (connect timeout=20)'))
2017-07-03 15:46:12,549 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C786D0>, 'Connection to 121.232.144.200 timed out. (connect timeout=20)'))
2017-07-03 15:46:17,407 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147BBF0>, 'Connection to 121.232.148.146 timed out. (connect timeout=20)'))
2017-07-03 15:46:19,164 utilFunction.py[line:25] INFO 59.66.135.35:1080 is ok!
2017-07-03 15:46:25,370 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488530>, 'Connection to 117.90.4.75 timed out. (connect timeout=20)'))
2017-07-03 15:46:25,591 utilFunction.py[line:31] ERROR EOF occurred in violation of protocol (_ssl.c:749)
2017-07-03 15:46:26,735 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01498250>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:27,891 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x014889D0>, 'Connection to 112.66.61.103 timed out. (connect timeout=20)'))
2017-07-03 15:46:27,923 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:46:28,839 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147BCF0>, 'Connection to 115.210.28.65 timed out. (connect timeout=20)'))
2017-07-03 15:46:28,930 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-03 15:46:28,950 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))
2017-07-03 15:46:28,989 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01498AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:30,000 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488A30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:30,031 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x014984B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:30,356 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2017-07-03 15:46:31,069 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C98370>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:32,175 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C98830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:32,556 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78850>, 'Connection to 117.90.3.4 timed out. (connect timeout=20)'))
2017-07-03 15:46:33,285 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C98CB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:33,379 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:46:33,598 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x014989D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:34,432 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488910>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:46:39,168 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488F50>, 'Connection to 117.90.1.93 timed out. (connect timeout=20)'))
2017-07-03 15:46:46,742 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x014986D0>, 'Connection to 121.232.144.136 timed out. (connect timeout=20)'))
2017-07-03 15:46:50,360 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C983B0>, 'Connection to 118.117.136.226 timed out. (connect timeout=20)'))
2017-07-03 15:46:50,458 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))
2017-07-03 15:46:53,601 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x014880B0>, 'Connection to 117.90.1.211 timed out. (connect timeout=20)'))
2017-07-03 15:46:54,438 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147BE10>, 'Connection to 123.149.162.130 timed out. (connect timeout=20)'))
2017-07-03 15:46:59,175 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147B930>, 'Connection to 121.232.146.234 timed out. (connect timeout=20)'))
2017-07-03 15:47:00,833 utilFunction.py[line:25] INFO 124.72.216.247:808 is ok!
2017-07-03 15:47:06,756 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147B1F0>, 'Connection to 1.83.107.30 timed out. (connect timeout=20)'))
2017-07-03 15:47:07,893 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78C90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:08,528 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78830>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:10,464 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01488450>, 'Connection to 182.129.241.7 timed out. (connect timeout=20)'))
2017-07-03 15:47:13,604 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01498AF0>, 'Connection to 117.90.5.157 timed out. (connect timeout=20)'))
2017-07-03 15:47:14,442 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78B50>, 'Connection to 117.90.0.246 timed out. (connect timeout=20)'))
2017-07-03 15:47:14,755 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69D90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:15,495 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69B30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:16,653 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CCD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:18,049 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147B190>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:19,364 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C6B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:27,899 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C69AD0>, 'Connection to 222.95.23.16 timed out. (connect timeout=20)'))
2017-07-03 15:47:28,533 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x01498AB0>, 'Connection to 114.99.5.75 timed out. (connect timeout=20)'))
2017-07-03 15:47:29,330 utilFunction.py[line:25] INFO 125.105.17.229:808 is ok!
2017-07-03 15:47:30,467 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C788F0>, 'Connection to 182.129.241.107 timed out. (connect timeout=20)'))
2017-07-03 15:47:34,759 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CE70>, 'Connection to 117.90.7.22 timed out. (connect timeout=20)'))
2017-07-03 15:47:35,904 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533CDD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:39,369 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147BA10>, 'Connection to 117.90.1.72 timed out. (connect timeout=20)'))
2017-07-03 15:47:48,535 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C130>, 'Connection to 182.129.240.160 timed out. (connect timeout=20)'))
2017-07-03 15:47:49,335 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C78810>, 'Connection to 60.214.154.2 timed out. (connect timeout=20)'))
2017-07-03 15:47:50,486 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-03 15:47:55,909 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533CF10>, 'Connection to 163.125.113.14 timed out. (connect timeout=20)'))
2017-07-03 15:47:55,983 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:47:57,125 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:47:59,419 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-03 15:48:08,542 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C670>, 'Connection to 121.232.145.107 timed out. (connect timeout=20)'))
2017-07-03 15:48:09,343 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CE50>, 'Connection to 117.90.3.3 timed out. (connect timeout=20)'))
2017-07-03 15:48:09,591 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C390>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:48:10,494 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5CB30>, 'Connection to 117.90.1.86 timed out. (connect timeout=20)'))
2017-07-03 15:48:17,128 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C030>, 'Connection to 117.90.2.65 timed out. (connect timeout=20)'))
2017-07-03 15:48:19,427 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0533C0D0>, 'Connection to 114.230.41.229 timed out. (connect timeout=20)'))
2017-07-03 15:48:29,350 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C9F0>, 'Connection to 117.90.2.11 timed out. (connect timeout=20)'))
2017-07-03 15:48:29,435 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:48:29,595 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0147BCB0>, 'Connection to 1.87.145.85 timed out. (connect timeout=20)'))
2017-07-03 15:48:30,498 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C030>, 'Connection to 121.232.147.135 timed out. (connect timeout=20)'))
2017-07-03 15:48:30,732 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D30790>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:48:31,298 utilFunction.py[line:31] ERROR ('Connection aborted.', BadStatusLine('<html>\r\n',))
2017-07-03 15:48:31,707 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x053109B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)))
2017-07-03 15:48:33,251 utilFunction.py[line:25] INFO 125.118.76.3:808 is ok!
2017-07-03 15:48:39,431 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C030>, 'Connection to 121.31.146.28 timed out. (connect timeout=20)'))
2017-07-03 15:48:42,677 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections',)))
2017-07-03 15:48:49,439 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0532C890>, 'Connection to 117.90.3.201 timed out. (connect timeout=20)'))
2017-07-03 15:48:51,730 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
2017-07-03 15:48:53,256 utilFunction.py[line:31] ERROR HTTPSConnectionPool(host='www.baidu.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00C5C0D0>, 'Connection to 119.254.84.90 timed out. (connect timeout=20)'))
